export const SWITCH_BUTTON = 'SWITCH_BUTTON'
export const CHANGE_INPUT_VALUE = 'CHANGE INPUT VALUE'
export const TOGGLE_USER_ACTIONS = 'TOGGLE USER ACTIONS'
export const TOGGLE_MODAL = 'TOGGLE MODAL'
export const HANDLE_DRAG = 'HANDLE DRAG'
export const ZERO_OUT_SLIDERS = 'ZERO OUT SLIDERS'

export const SIGN_OUT = 'SIGN OUT'

export const SIGN_IN = 'SIGN IN'
export const SIGN_IN_SUCCESSFUL = 'SIGN IN SUCCESSFUL'
export const SIGN_IN_FAILED = 'SIGN IN FAILED'

export const FORGOT_PASSWORD = 'FORGOT PASSWORD'
export const FORGOT_PASSWORD_SUCCESSFUL = 'FORGOT PASSWORD SUCCESSFUL'
export const FORGOT_PASSWORD_FAILED = 'FORGOT PASSWORD FAILED'

export const WEIGH_IN = 'WEIGH IN'
export const WEIGH_IN_SUCCESSFUL = 'WEIGH IN SUCCESSFUL'
export const WEIGH_IN_FAILED = 'WEIGH IN FAILED'